### ISSUE TITLE
arguments missing 

### ISSUE THREAD

**Issue by Allenpai1** [JUNJIE99/VISTA_Evaluation_FineTuning#1]
Dear sir/madam, 

I try to train the model and seems like that the the code for arguments are missing.

 from arguments import ModelArguments, DataArguments, \
    RetrieverTrainingArguments as TrainingArguments

Thanks for helping.

**Comment by JUNJIE99** [comment]
For training or fine-tuning our model, you need to use the corresponding `bash` file in the folder instead of directly run `train.py`. 

We have provided all necessary arguments in the `bash` file.

**Comment by craigkdl** [comment]
Hi, I'm also getting the error when running with the bash file,
```ModuleNotFoundError: No module named 'arguments'```

My understanding is line, 
```sys.path.append('./FlagEmbedding/baai_general_embedding/downstream')```
 in `run_ds_cirr.py` should add the path where `arguments.py` could be found. 

If the `./FlagEmbedding/baai_general_embedding/` is pointing to [FlagEmbedding repo](https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/baai_general_embedding), at this moment I could not find the `downstream`. I only see `arguments.py` in the `FlagEmbedding/baai_general_embedding/finetune`, but the arguments seem to miss some specific ones for visual_bge, such as `train_text_tower` and `train_vision_tower`.
