### ISSUE TITLE
stage 1 checkpoints

### ISSUE THREAD

**Issue by olccihyeon** [JUNJIE99/VISTA_Evaluation_FineTuning#2]
hello.

I'm currently training with a dataset for stage 2 and would like to know if you could provide me with the model checkpoints for stage 1 as well.a

**Comment by JUNJIE99** [comment]
Hi, I have sent the model checkpoint of stage 1 to your email. Please check.

**Comment by dongguanting** [comment]
> Hi, I have sent the model checkpoint of stage 1 to your email. Please check.

Hello, I also reproduce Vista stage 2, could you please also email me the stage 1 checkpoint?

My email is in my github personal page.

Many Thanks!
